apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[Stable] ControllerConfig"
crd: 0000_10_controllerconfig.crd.yaml
tests:
  onCreate:
  - name: Should be able to create a minimal ControllerConfig
    initial: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: ControllerConfig
      spec: {} # No spec is required for a ControllerConfig
    expected: |
      apiVersion: apiserver.openshift.io/v1
      kind: ControllerConfig
      spec: {}
      